service: oto

package:
  exclude:
    - src/**
    - README.md

provider:
  name: aws
  region: eu-west-1
  stage: ${opt:stage, "dev"}
  runtime: nodejs10.x
  memorySize: 128
  timeout: 15
  environment: ${file(./env/sls.env.json):${opt:stage,"dev"}}

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  stages:
    dev:
      domain: oto-dev.becode.xyz
      domainEnabled: true
    production:
      domain: oto.becode.xyz
      domainEnabled: true
  customDomain:
    domainName: ${self:custom.stages.${self:provider.stage}.domain}
    certificateName: "*.becode.xyz"
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
    enabled: ${self:custom.stages.${self:provider.stage}.domainEnabled}

functions:
  gh-secret-handler:
    handler: bin/oto.handler
    events:
      - http: GET /
      - http: "GET {proxy+}"
